USE job_data;

CREATE TABLE user (
    user VARCHAR(255) PRIMARY KEY ,
    password VARCHAR(255)
);

CREATE TABLE job_data (
  JOB_ID VARCHAR(255),
  JOB_TITLE VARCHAR(255),
  JOB_ACTIVEDATE VARCHAR(255),
  DATE_VIEW VARCHAR(255),
  EMP_NAME VARCHAR(255),
  BENEFIT_NAME TEXT,
  LINK_JOB VARCHAR(255),
  JOB_SALARY_STRING VARCHAR(255),
  LOCATION_NAME_ARR TEXT
);